name: web job
on:
  pull_request:
    branches:
      - master
    paths:
      - "web/**"
      - "!server/**"
      - "!mobile/**"

  push:
    branches:
      - master
    paths:
      - "web/**"
      - "!server/**"
      - "!mobile/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [10.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./web
        run: yarn install

      - name: Build
        working-directory: ./web
        run: yarn build

        env:
          CI: true
